name = "node"
description = "Node.js runtime"
homepage = "https://nodejs.org/"
versions = ["18.17.1", "20.12.0"]

[[tool]]
version = "18.17.1"
repository = "node/18.17.1"

[[tool]]
version = "20.12.0"
repository = "node/20.12.0"
